AWSTemplateFormatVersion: '2010-09-09'
Description: '[Social Media Dashboard] CDN Stack'

Parameters:

  ParentStackName:
    Type: String

  OriginDomainName:
    Type: String

  CdnDomainName:
    Type: String

  CdnAcmCertificateArn:
    Type: String
    AllowedPattern: ^arn:aws:acm:us-east-1:[0-9]{12}:certificate/[\w\-]+$

Mappings: 
  Policies: 
    CachePolicyId: 
      ManagedCachingOptimized: 658327ea-f89d-4fab-a63d-7e88639e58f6
      ManagedCachingDisabled: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad
      ManagedCachingOptimizedForUncompressedObjects: b2884449-e4de-46a7-ac36-70bc7f1ddd6d
      ManagedElementalMediaPackage: 08627262-05a9-4f76-9ded-b50ca2e3a84f
    OriginRequestPolicyId:
      ManagedUserAgentRefererHeaders: acba4595-bd28-49b8-b9fe-13317c0390fa
      ManagedAllViewer: 216adef6-5c7f-47e4-b989-5492eafa07d3
      ManagedCORSS3Origin: 88a5eaf4-2fd4-4709-b370-b4c650ea3fcf
      ManagedCORSCustomOrigin: 59781a5b-3903-41f3-afcb-af62929ccde1
      ManagedElementalMediaTailorPersonalizedManifests: 775133bc-15f2-49f9-abea-afb2e0bf67d2

Resources:

  Distribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        Comment: !Ref ParentStackName
        Aliases:
          - !Ref CdnDomainName
        ViewerCertificate:
          AcmCertificateArn: !Ref CdnAcmCertificateArn
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2019
        HttpVersion: http2
        IPV6Enabled: true
        Origins:
          - Id: amazon-elasticsearch
            DomainName: !Ref OriginDomainName
            CustomOriginConfig:
              OriginProtocolPolicy: https-only
              OriginKeepaliveTimeout: 60
              OriginReadTimeout: 60
            #OriginCustomHeaders:
            #  - HeaderName: Host
            #    HeaderValue: !Ref OriginDomainName
        DefaultCacheBehavior:
          TargetOriginId: amazon-elasticsearch
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods: [ GET, HEAD, OPTIONS, PUT, PATCH, POST, DELETE ]
          CachedMethods: [ GET, HEAD ]
          CachePolicyId: !FindInMap [Policies, CachePolicyId, ManagedCachingDisabled]
          OriginRequestPolicyId: !FindInMap [Policies, OriginRequestPolicyId, ManagedAllViewer]
          Compress: true
        #CustomErrorResponses:
        #  - ErrorCode: 403
        #    ErrorCachingMinTTL: 0
        #  - ErrorCode: 503
        #    ErrorCachingMinTTL: 0

Outputs: {}
