# https://github.com/awslabs/aws-sam-codebuild-ci
version: 0.2
phases:
  install:
    runtime-versions:
        python: 3.7
    commands:
      - pip install cfn-lint
  build:
    commands:
      - pip install cfn-lint
      #- aws cloudformation package --template-file template.yaml --s3-bucket ${PACKAGE_BUCKET} --output-template-file packaged-template.yaml
      - sam build
      - sam package --template-file template.yml --s3-bucket ${PACKAGE_BUCKET} --output-template-file packaged-template.yml
      #- sam deploy --template-file packaged-template.yml --stack-name social-media-dashboard
artifacts:
  files:
    - packaged-template.yml
