AWSTemplateFormatVersion: '2010-09-09'
Description: '[Social Media Dashboard] CDN Stack'

Parameters:

  ParentStackName:
    Type: String

  OriginDomainName:
    Type: String

  CdnDomainName:
    Type: String

  CdnAcmCertificateArn:
    Type: String
    AllowedPattern: ^arn:aws:acm:us-east-1:[0-9]{12}:certificate/[\w\-]+$

Resources:

  Distribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        Comment: !Ref ParentStackName
        Aliases:
          - !Ref CdnDomainName
        ViewerCertificate:
          AcmCertificateArn: !Ref CdnAcmCertificateArn
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2019
        HttpVersion: http2
        IPV6Enabled: true
        Origins:
          - Id: amazon-elasticsearch
            DomainName: !Ref OriginDomainName
            CustomOriginConfig:
              OriginProtocolPolicy: https-only
            #OriginCustomHeaders:
            #  - HeaderName: Host
            #    HeaderValue: !Ref OriginDomainName
        DefaultCacheBehavior:
          TargetOriginId: amazon-elasticsearch
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods: [ GET, HEAD, OPTIONS, PUT, PATCH, POST, DELETE ]
          CachedMethods: [ GET, HEAD ]
          CachePolicyId: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad
          OriginRequestPolicyId: 216adef6-5c7f-47e4-b989-5492eafa07d3
          Compress: true
        CacheBehaviors:
          - PathPattern: '*.css'
            TargetOriginId: amazon-elasticsearch
            ViewerProtocolPolicy: redirect-to-https
            AllowedMethods: [ GET, HEAD ]
            CachedMethods: [ GET, HEAD ]
            CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6
            OriginRequestPolicyId: 216adef6-5c7f-47e4-b989-5492eafa07d3
            Compress: true
          - PathPattern: '*.svg'
            TargetOriginId: amazon-elasticsearch
            ViewerProtocolPolicy: redirect-to-https
            AllowedMethods: [ GET, HEAD ]
            CachedMethods: [ GET, HEAD ]
            CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6
            OriginRequestPolicyId: 216adef6-5c7f-47e4-b989-5492eafa07d3
            Compress: true
          - PathPattern: '*/bundles/*.js'
            TargetOriginId: amazon-elasticsearch
            ViewerProtocolPolicy: redirect-to-https
            AllowedMethods: [ GET, HEAD ]
            CachedMethods: [ GET, HEAD ]
            CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6
            OriginRequestPolicyId: 216adef6-5c7f-47e4-b989-5492eafa07d3
            Compress: true

Outputs: {}
