AWSTemplateFormatVersion: '2010-09-09'
Transform: "AWS::Serverless-2016-10-31"
Description: '[Social Media Dashboard] Labeling Job Stack'

Parameters:

  ParentStackName:
    Type: String

  AlarmTopic:
    Type: String

  TweetStreamArn:
    Type: String

  UserPoolId:
    Type: String

  Bucket:
    Type: String

  S3ObjectsFunctionArn:
    Type: String

  PowertoolsLayer:
    Type: String

  CustomResourceHelperLayer:
    Type: String

  LabelingUiTemplateLayer:
    Type: String

Globals:
  Function:
    Runtime: python3.8
    Handler: index.lambda_handler
    Layers:
      - !Ref PowertoolsLayer
      - !Ref CustomResourceHelperLayer

Resources:

  GroundTruthStreamFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: '[Social Media Dashboard] Put tweets to topic for Ground Truth'
      CodeUri: functions/put_sns_topic/
      MemorySize: 192
      Timeout: 10
      Tracing: Active
      Layers:
        - !Sub "arn:aws:lambda:${AWS::Region}:580247275435:layer:LambdaInsightsExtension:2"
      Environment:
        Variables:
          LOG_LEVEL: INFO
          SERVICE_NAME: 'put_labeling_topic'
          INPUT_TOPIC_ARN: !Ref GroundTruthInputTopic
          TWEET_DAY_THRESHOLD: 90
      Events:
        Stream:
          Type: Kinesis
          Properties:
            Stream: !Ref TweetStreamArn
            StartingPosition: LATEST
            ParallelizationFactor: 1
            BatchSize: 100
            MaximumRecordAgeInSeconds: 300
      Policies:
        - CloudWatchLambdaInsightsExecutionRolePolicy
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action: 'sns:Publish'
              Resource: !Ref GroundTruthInputTopic

  GroundTruthStreamFunctionErrorsAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: Errors of GroundTruth Input Function
      Namespace: AWS/Lambda
      MetricName: Errors
      Dimensions: 
        - Name: FunctionName
          Value: !Ref GroundTruthStreamFunction
      Statistic: Sum
      Period: 60
      AlarmActions: 
        - !Ref AlarmTopic
      OKActions: 
        - !Ref AlarmTopic
      ComparisonOperator: GreaterThanThreshold
      Threshold: 0
      EvaluationPeriods: 1
      DatapointsToAlarm: 1

  GroundTruthInputTopic:
    Type: AWS::SNS::Topic
    Properties: 
      DisplayName: GroundTruthInputTopic
      Tags: 
        - Key: cloudformation:stack-name
          Value: !Ref AWS::StackName
        - Key: cloudformation:stack-id
          Value: !Ref AWS::StackId
        - Key: cloudformation:logical-id
          Value: GroundTruthInputTopic

  GroundTruthOutputTopic:
    Type: AWS::SNS::Topic
    Properties: 
      DisplayName: GroundTruthOutputTopic
      Tags: 
        - Key: cloudformation:stack-name
          Value: !Ref AWS::StackName
        - Key: cloudformation:stack-id
          Value: !Ref AWS::StackId
        - Key: cloudformation:logical-id
          Value: GroundTruthOutputTopic

  GroundTruthAssets:
    Type: Custom::S3Objects
    Properties:
      ServiceToken: !Ref S3ObjectsFunctionArn
      Bucket: !Ref Bucket
      Path: groundtruth/assets/
      SourceLayerArn: !Ref LabelingUiTemplateLayer

  GroundTruthExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action: "sts:AssumeRole"
            Principal:
              Service: sagemaker.amazonaws.com
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSageMakerGroundTruthExecution

  GtRecipePreHumanTaskFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: '[Ground Truth] PreProcess'
      CodeUri: functions/pre_human_task/

  TweetClassification:
    Type: Custom::LabelingJob
    Properties:
      ServiceToken: !GetAtt StreamingLabelingJobFunction.Arn
      LabelingJobName: !Sub 'TweetClassification-v${GroundTruthAssets.LayerVersion}'
      InputTopicArn: !Ref GroundTruthInputTopic
      OutputTopicArn: !Ref GroundTruthOutputTopic
      S3OutputPath: !Sub 's3://${Bucket}/groundtruth/jobs/'
      WorkteamArn: !Ref Workteam
      HumanTaskTitle: !Sub 'Tweet Classification v${GroundTruthAssets.LayerVersion}'
      HumanTaskDescription: !Sub 'Tweet Classification v${GroundTruthAssets.LayerVersion}'
      UiTemplateS3Uri: !Sub 's3://${GroundTruthAssets.Bucket}/${GroundTruthAssets.Path}tweet-classification.html'
      PreHumanTaskLambdaArn: !GetAtt GtRecipePreHumanTaskFunction.Arn

  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref UserPoolId
      ClientName: sagemaker-groundtruth-app-client
      GenerateSecret: true
      RefreshTokenValidity: 30
      AccessTokenValidity: 1
      IdTokenValidity: 1
      ExplicitAuthFlows: 
        - ALLOW_CUSTOM_AUTH
        - ALLOW_USER_PASSWORD_AUTH
        - ALLOW_USER_SRP_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
      # App client settings
      SupportedIdentityProviders: 
        - COGNITO
      CallbackURLs: 
        - 'https://d3c4ozbynv3jtc.cloudfront.net'  # Dummy URL
      AllowedOAuthFlowsUserPoolClient: true
      AllowedOAuthFlows: 
        - code
        - implicit
      AllowedOAuthScopes: 
        - email
        - openid
        - profile

  WorkforceGroup:
    Type: AWS::Cognito::UserPoolGroup
    Properties:
      GroupName: GroundTruthWorkforce
      Description: Labeling Workforce Group
      UserPoolId: !Ref UserPoolId

  Workteam:
    Type: AWS::SageMaker::Workteam
    Properties:
      WorkteamName: KibanaUsers
      Description: Kibana Users
      MemberDefinitions: 
        - CognitoMemberDefinition: 
            CognitoClientId: !Ref UserPoolClient
            CognitoUserGroup: !Ref WorkforceGroup
            CognitoUserPool: !Ref UserPoolId
      #NotificationConfiguration: 
      #  NotificationConfiguration
      Tags: 
        - Key: cloudformation:stack-name
          Value: !Ref AWS::StackName
        - Key: cloudformation:stack-id
          Value: !Ref AWS::StackId
        - Key: cloudformation:logical-id
          Value: GroundTruthOutputTopic

  StreamingLabelingJobFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: '[Custom Resource] Streaming Labe lingJob'
      CodeUri: custom_resources/streaming_labeling_job/
      Environment:
        Variables:
          GROUND_TRUTH_ROLE_ARN: !GetAtt GroundTruthExecutionRole.Arn
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'sagemaker:CreateLabelingJob'
                - 'sagemaker:StopLabelingJob'
              Resource:
                - !Sub 'arn:aws:sagemaker:${AWS::Region}:${AWS::AccountId}:labeling-job/*'
            - Effect: Allow
              Action:
                - 'sqs:DeleteQueue'
              Resource:
                - !Sub 'arn:aws:sqs:${AWS::Region}:${AWS::AccountId}:GroundTruth-*'
            - Effect: Allow
              Action:
                - 'iam:PassRole'
              Resource:
                - !GetAtt GroundTruthExecutionRole.Arn

Outputs:

  GroundTruthStreamFunction:
    Value: !Ref GroundTruthStreamFunction
  
  #LabelingJobName:
  #  Value: !Ref StreamingLabelingJob
